title: Giang Luong (Thi)
description: Data Analyst/ Data Scientist | Economic Background | 3+ Years BI Expertise | Power BI, Google Data Studio, Python Modeling.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
